spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_attendance
    username: root
    password: Thilina
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
      secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437 #secret key for jwt token